import PDFDocument from "pdfkit"

export function createPDFWithOCRLayer(
  title: string,
  classification: string,
  extractedText: string,
  confidence?: number,
  author?: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const pdf = new PDFDocument({
      size: "A4",
      margin: 40,
    })

    const chunks: Buffer[] = []

    pdf.on("data", (chunk) => chunks.push(chunk))
    pdf.on("error", reject)

    pdf.font("Helvetica-Bold").fontSize(24).text(title)

    pdf.fontSize(10).font("Helvetica").fillColor("#666").text(`Classification: ${classification}`)

    if (confidence) {
      pdf.text(`Confidence Score: ${(confidence * 100).toFixed(1)}%`)
    }

    pdf.fillColor("#000").fontSize(1).text("")

    // Horizontal line 
    pdf
      .moveTo(40, pdf.y)
      .lineTo(pdf.page.width - 40, pdf.y)
      .stroke()

    pdf.fontSize(1).text("")

    // Main content
    pdf
      .font("Helvetica")
      .fontSize(11)
      .text(extractedText, {
        align: "justify",
        width: pdf.page.width - 80,
      })

    const footerText = `Generated by DocIntelligence | ${new Date().toLocaleString()}`
    const footerY = pdf.page.height - 60 // Position 60 points from bottom

    pdf
      .fontSize(8)
      .fillColor("#999")
      .text(footerText, 40, footerY, { // ✅ Explicitly set x, y coordinates
        align: "center",
        width: pdf.page.width - 80,
      })

    pdf.end()

    pdf.on("end", () => {
      resolve(Buffer.concat(chunks))
    })
  })
}
